### PR TITLE
Add friend and articles components initial check in of file structure and some code

### PR DESCRIPTION
**Pull request by cdouglass516**
This is the first check in for the components friends, articles and /modules/FriendsManager.js. Mainly this is the file structure and initial code. It also contains the addition of a modules folder where the data layer logic can be found.

### CODE REVIEW

**Review by Chadwell-Clark — CHANGES_REQUESTED** [review]
I am getting an infinite loop in the fetch to `http://localhost:8088/users` from `FriendsManager` 
I think your useEffect in the friends detail needs a dependency array

**Comment by cdouglass516** [comment]
> I am getting an infinite loop in the fetch to `http://localhost:8088/users` from `FriendsManager`
> I think your useEffect in the friends detail needs a dependency array

Chad I am not sure what shape that is in. I was using to test some other code may not have put it back exactly right.

**Review by Chadwell-Clark — APPROVED** [review]
Looks Good. I installed the autocomplete hint and it works very nicely.

**Review by coltmay — APPROVED** [review]
Looks good, we may need to move <FriendsCard> to the friends route in ApplicationViews.

**Pull request merged**
